name: Preprod CI

on:
  push:
    branches: [ preprod ]
  pull_request:
    branches: [ preprod ]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i
        working-directory: backend
      - run: npm run lint
        working-directory: backend

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i
        working-directory: frontend
      - run: npm run lint
        working-directory: frontend
